[platformio]
default_envs = pro_trinket_5v

[env:pro_trinket_5v]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino

[env:native]
platform = native
test_framework = unity
build_flags = -I include
